"""
main.py — FastAPI application entry point.

This is the REST API that serves data to the React portal (Phase 7).
It connects the frontend to:
  - Iceberg table metadata (datasets)
  - Data lineage graph
  - ML experiment results
  - Pipeline health status

Usage:
    source .venv/bin/activate
    uvicorn backend.main:app --reload --port 8000

API docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.routers import datasets, lineage, ml_results, health

# Create the FastAPI application
app = FastAPI(
    title="Telemetry AI Data Platform API",
    description="REST API for dataset discovery, lineage, ML results, and pipeline health",
    version="1.0.0",
)

# --- CORS Middleware ---
# Allow the React dev server (port 5173) to make requests to this API.
# Without this, browsers block cross-origin requests for security.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # React Vite dev server
        "http://localhost:3000",   # Fallback for other dev servers
    ],
    allow_credentials=True,
    allow_methods=["*"],           # Allow all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],           # Allow all headers
)

# --- Mount routers ---
# Each router handles a different domain of the API.
# prefix="/api/..." means all routes in that router start with /api/...
app.include_router(datasets.router, prefix="/api/datasets", tags=["Datasets"])
app.include_router(lineage.router, prefix="/api/lineage", tags=["Lineage"])
app.include_router(ml_results.router, prefix="/api/ml", tags=["ML"])
app.include_router(health.router, prefix="/api/health", tags=["Health"])


@app.get("/health")
def root_health_check():
    """Simple health check — returns OK if the API is running."""
    return {"status": "ok", "service": "telemetry-api"}
